---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  selector:
    app: alertmanager
  ports:
    - name: alertmanager
      protocol: TCP
      port: 9093
      targetPort: 9093
  externalIPs:
    - 172.17.0.1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: alertmanager
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: alertmanager
          image: bitnami/alertmanager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9093