---
apiVersion: v1
kind: Service
metadata:
  name: alerttrap
spec:
  selector:
    app: alerttrap
  ports:
    - name: alerttrap
      protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerttrap
  labels:
    app: alerttrap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerttrap
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: alerttrap
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: alerttrap
          image: ghcr.io/ltkh/alerttrap:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          args:
            - '-web-dir=/data/web'
            - '-config=/alerttrap-conf/alerttrap.yml'
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /alerttrap-conf
              name: alerttrap-volume
      volumes:
        - name: alerttrap-volume
          configMap:
            name: alerttrap-configuration

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alerttrap-configuration
  namespace: default
data:
  alerttrap.yml: |-
    global:
      listen_address:   ":8000"
      cert_file:        ""
      cert_key:         ""
      alerts_limit:     5000
      alerts_resolve:   180
      alerts_delete:    600
      
      db:
        client:         "mysql"
        conn_string:    "root:example@(mysql.default.svc.cluster.local)/alerttrap?parseTime=true"
        history_days:   7

      security:
        admin_user:     "admin"
        admin_password: "password" 

    menu:
      - id: "kubernetes"
        name: "Kubernetes"
        class: "fa fa-th-large"
        nodes:
          - id: "prod"
            name: "Prod"
            href: "/api/v1/alerts"
            tags: ["alertgroup","namespace","pod"]
          

    #extension_rules:
    #  - source_matchers: ['{host=~"host-2.*"}']
    #    labels:
    #      test: "alert2" 
    #  - source_matchers: ['{host=~"host-5.*"}']
    #    labels:
    #      test: "alert5" 
    #      test1: "тестовый раздел" 