---
apiVersion: v1
kind: Service
metadata:
  name: etcd-client
spec:
  type: LoadBalancer
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd

---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    app: etcd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      name: etcd
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:latest
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: 'yes'
          args:
            #- '--name etcd0'
            #- '--listen-peer-urls http://0.0.0.0:2380'
            #- '--listen-client-urls http://0.0.0.0:2379'
            #- '--advertise-client-urls http://${HOSTNAME}.etcd:2379'
            #- '--initial-advertise-peer-urls http://${HOSTNAME}:2380'
            #- '--initial-cluster etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380'
            #- '--initial-cluster-state new'
            #- '--initial-cluster-token etcd-cluster-1'
            #- '--data-dir /var/run/etcd/default.etcd'
          volumeMounts:
            - mountPath: /var/run/etcd
              name: etcd-pv
      volumes:
        - name: etcd-pv
          persistentVolumeClaim:
            claimName: etcd-pvc