---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
  externalIPs:
    - 188.225.38.102

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: grafana
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      #serviceAccountName: default-token
      #automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-volume
      volumes:
        - name: grafana-volume
          hostPath:
            path: /home/monit/volumes/grafana
            type: Directory