---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: mysqld-exporter
      protocol: TCP
      port: 9104
      targetPort: 9104

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.28
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: alerttrap
            - name: MYSQL_ROOT_PASSWORD
              value: alerttrap
        - name: mysqld-exporter
          image: prom/mysqld-exporter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              value: root:alerttrap@(localhost:3306)/alerttrap
          #args:
          #  - '--network my-mysql-network'
