---
apiVersion: v1
kind: Service
metadata:
  name: vmalert
spec:
  selector:
    app: vmalert
  ports:
    - name: vmalert
      protocol: TCP
      port: 8880
      targetPort: 8880
  externalIPs:
    - 172.17.0.1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmalert
  labels:
    app: vmalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmalert
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: vmalert
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: vmalert
          image: victoriametrics/vmalert:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8880
          args:
            - '-rule=/vmalert-conf/alert.rules'
            - '-datasource.url=http://vmselect.default.svc.cluster.local:8481/select/0/prometheus'
            - '-remoteWrite.url=http://vminsert.default.svc.cluster.local:8480/insert/0/prometheus'
            - '-notifier.url=http://alertmanager.default.svc.cluster.local:9093'
          volumeMounts:
            - mountPath: /vmalert-conf
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: vmalert-configuration

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmalert-configuration
  namespace: default
data:
  alert.rules: |-
    groups:
      - name: "grafana"
        rules:
          - alert: grafana_emails_sent_failed
            expr: grafana_emails_sent_failed{} > 0


