---
apiVersion: v1
kind: Service
metadata:
  name: vminsert
spec:
  selector:
    app: vminsert
  ports:
    - name: vminsert
      protocol: TCP
      port: 8480
      targetPort: 8480

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vminsert
  labels:
    app: vminsert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vminsert
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: vminsert
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: vminsert
          image: victoriametrics/vminsert:latest
          resources:
            requests:
              cpu: "0.05"
              memory: "50Mi"
              ephemeral-storage: "50Mi"
            limits:
              cpu: "0.1"
              memory: "100Mi"
              ephemeral-storage: "100Mi"
          #imagePullPolicy: Always
          ports:
            - containerPort: 8480
          args:
            - '-storageNode=vmstorage.default.svc.cluster.local:8400'
