---
apiVersion: v1
kind: Service
metadata:
  name: vmselect
spec:
  selector:
    app: vmselect
  ports:
    - name: vmselect
      protocol: TCP
      port: 8481
      targetPort: 8481

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmselect
  labels:
    app: vmselect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmselect
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: vmselect
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: vmselect
          image: victoriametrics/vmselect:v1.69.0-cluster
          resources:
            requests:
              cpu: "0.05"
              memory: "50Mi"
              ephemeral-storage: "50Mi"
            limits:
              cpu: "0.05"
              memory: "100Mi"
              ephemeral-storage: "100Mi"
          #imagePullPolicy: Always
          ports:
            - containerPort: 8481
          args:
            - '-storageNode=vmstorage.default.svc.cluster.local:8401'
