---
apiVersion: v1
kind: Service
metadata:
  name: vmstorage
spec:
  selector:
    app: vmstorage
  ports:
    - name: vmstorage8400
      protocol: TCP
      port: 8400
      targetPort: 8400
    - name: vmstorage8401
      protocol: TCP
      port: 8401
      targetPort: 8401
    - name: vmstorage8482
      protocol: TCP
      port: 8482
      targetPort: 8482

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmstorage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmstorage
  labels:
    app: vmstorage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmstorage
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: vmstorage
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: vmstorage
          image: victoriametrics/vmstorage:v1.69.0-cluster
          resources:
            requests:
              cpu: "0.1"
              memory: "100Mi"
            limits:
              cpu: "0.25"
              memory: "200Mi"
          #imagePullPolicy: Always
          ports:
            - containerPort: 8482
          args: 
            - '-storageDataPath=/vmstorage-data'
          volumeMounts:
            - mountPath: /vmstorage-data
              name: vmstorage-pv
      volumes:
        - name: vmstorage-pv
          persistentVolumeClaim:
            claimName: vmstorage-pvc

#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: vmstorage-volume
#spec:
#  accessModes:
#  - ReadWriteMany
#  resources:
#    requests:
#      storage: 5Gi
