---
apiVersion: v1
kind: Service
metadata:
  name: vmui
spec:
  selector:
    app: vmui
  ports:
    - name: vmui
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmui
  labels:
    app: vmui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmui
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: vmui
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: vmui
          image: victoriametrics/vmui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
